### ISSUE TITLE
소셜 로그인 에러

### ISSUE THREAD

**Issue by iz4blue** [pythonkr/pyconkr-2018#88]
소셜 로그인이 동작하지 않는 듯 보여집니다.

관련된 로그 report 합니다.
로그 캡춰를 잘못하여 줄바꿈 처리가 이상하게 되어 있습니다. 넓은 이해심으로 수동으로 파악 부탁드립니다.

```
self.model._meta.object_name
allauth.socialaccount.models.DoesNotExist: SocialApp matching query does not exist.
Internal Server Error: /2018/accounts/twitter/login/
Traceback (most recent call last):
File "--python-evn-path--/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "--python-evn-path--/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "--python-evn-path--/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "--python-evn-path--/site-packages/django/core/handlers/base.py", line 185, i
n _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "--python-evn-path--/site-packages/allauth/socialaccount/providers/oauth/view
s.py", line 40, in view
return self.dispatch(request, *args, **kwargs)
File "--python-evn-path--/site-packages/allauth/socialaccount/providers/oauth/view
s.py", line 67, in dispatch
client = self._get_client(request, callback_url)
File "--python-evn-path--/site-packages/allauth/socialaccount/providers/oauth/view
s.py", line 45, in _get_client
app = provider.get_app(request)
File "--python-evn-path--/site-packages/allauth/socialaccount/providers/base.py",
line 52, in get_app
return SocialApp.objects.get_current(self.id, request)
File "--python-evn-path--/site-packages/allauth/socialaccount/models.py", line 40,
in get_current
provider=provider)
File "--python-evn-path--/site-packages/django/db/models/manager.py", line 85, in
manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "--python-evn-path--/site-packages/django/db/models/query.py", line 380, in g
et
self.model._meta.object_name
allauth.socialaccount.models.DoesNotExist: SocialApp matching query does not exist.
```

**Comment by NohSeho** [comment]
기능이 동작하지 않는 건 문제가 있긴한데, 지금 사이트에 소셜 로그인이 있나요?

**Comment by iz4blue** [comment]
그러네요. 소셜 로그인은 없는 것 같습니다.
소셜앱은 어떤 기능으로 추가가 되어 있는 걸까요?
